### ISSUE TITLE
1.16 Outdated VotingPlugin (Maybe?)

### ISSUE THREAD

**Issue by Burchard36** [BlockyBorzan/BlockyRanks#13]
Hello; i am running both the latest version of BlockyRanks & VotingPlugin (https://www.spigotmc.org/resources/votingplugin.15358/)

Voting plugin is loaded, connected to my MySQL and shows up green in /plugins and /vote works, so i know that VotingPlugin is 100% enabled; however when adding:

```yaml
        voting-requirements:
        - votes-metric: all-time-total
          votes-needed: 1
```

To one of my /branches .yml [However i stumble upon this issue](https://pastebin.com/bckr0deA)

This is on 1.16.4 server version as well
